/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/ui/AppLogo.vue')['default']
    CancelButton: typeof import('./src/components/ui/CancelButton.vue')['default']
    ConfirmButton: typeof import('./src/components/ui/ConfirmButton.vue')['default']
    DesktopNavBar: typeof import('./src/components/layout/DesktopNavBar.vue')['default']
    DiagnosticDetails: typeof import('./src/components/tests/DiagnosticDetails.vue')['default']
    InfoCard: typeof import('./src/components/patients/InfoCard.vue')['default']
    MobileNavBar: typeof import('./src/components/layout/MobileNavBar.vue')['default']
    PageTitle: typeof import('./src/components/ui/PageTitle.vue')['default']
    PatientDetails: typeof import('./src/components/tests/PatientDetails.vue')['default']
    PatientForm: typeof import('./src/components/patients/PatientForm.vue')['default']
    PatientPatientsList: typeof import('./src/components/tests/PatientPatientsList.vue')['default']
    PatientsList: typeof import('./src/components/patients/PatientsList.vue')['default']
    PersonalInfos: typeof import('./src/components/profile/PersonalInfos.vue')['default']
    ProfessionalInfos: typeof import('./src/components/profile/ProfessionalInfos.vue')['default']
    RemakeButton: typeof import('./src/components/ui/RemakeButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/profile/Sidebar.vue')['default']
    SubpageTitle: typeof import('./src/components/ui/SubpageTitle.vue')['default']
    TestsList: typeof import('./src/components/tests/TestsList.vue')['default']
  }
}
