/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/change-password': RouteRecordInfo<'/change-password', '/change-password', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/edit-patient': RouteRecordInfo<'/edit-patient', '/edit-patient', Record<never, never>, Record<never, never>>,
    '/infos': RouteRecordInfo<'/infos', '/infos', Record<never, never>, Record<never, never>>,
    '/manual': RouteRecordInfo<'/manual', '/manual', Record<never, never>, Record<never, never>>,
    '/new-test': RouteRecordInfo<'/new-test', '/new-test', Record<never, never>, Record<never, never>>,
    '/patient-details': RouteRecordInfo<'/patient-details', '/patient-details', Record<never, never>, Record<never, never>>,
    '/patient-infos': RouteRecordInfo<'/patient-infos', '/patient-infos', Record<never, never>, Record<never, never>>,
    '/patient-profile': RouteRecordInfo<'/patient-profile', '/patient-profile', Record<never, never>, Record<never, never>>,
    '/patient-test-result': RouteRecordInfo<'/patient-test-result', '/patient-test-result', Record<never, never>, Record<never, never>>,
    '/patients': RouteRecordInfo<'/patients', '/patients', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/register-patient': RouteRecordInfo<'/register-patient', '/register-patient', Record<never, never>, Record<never, never>>,
    '/sign-in': RouteRecordInfo<'/sign-in', '/sign-in', Record<never, never>, Record<never, never>>,
    '/terms-of-use': RouteRecordInfo<'/terms-of-use', '/terms-of-use', Record<never, never>, Record<never, never>>,
    '/test-finished': RouteRecordInfo<'/test-finished', '/test-finished', Record<never, never>, Record<never, never>>,
    '/test-history': RouteRecordInfo<'/test-history', '/test-history', Record<never, never>, Record<never, never>>,
    '/test-progress': RouteRecordInfo<'/test-progress', '/test-progress', Record<never, never>, Record<never, never>>,
    '/test-result': RouteRecordInfo<'/test-result', '/test-result', Record<never, never>, Record<never, never>>,
  }
}
