/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/sign-in': RouteRecordInfo<'/auth/sign-in', '/auth/sign-in', Record<never, never>, Record<never, never>>,
    '/patient/change-password': RouteRecordInfo<'/patient/change-password', '/patient/change-password', Record<never, never>, Record<never, never>>,
    '/patient/contact': RouteRecordInfo<'/patient/contact', '/patient/contact', Record<never, never>, Record<never, never>>,
    '/patient/infos': RouteRecordInfo<'/patient/infos', '/patient/infos', Record<never, never>, Record<never, never>>,
    '/patient/patients': RouteRecordInfo<'/patient/patients', '/patient/patients', Record<never, never>, Record<never, never>>,
    '/patient/profile': RouteRecordInfo<'/patient/profile', '/patient/profile', Record<never, never>, Record<never, never>>,
    '/patient/terms-of-use': RouteRecordInfo<'/patient/terms-of-use', '/patient/terms-of-use', Record<never, never>, Record<never, never>>,
    '/patient/test-history': RouteRecordInfo<'/patient/test-history', '/patient/test-history', Record<never, never>, Record<never, never>>,
    '/patient/test-result': RouteRecordInfo<'/patient/test-result', '/patient/test-result', Record<never, never>, Record<never, never>>,
    '/professional/change-password': RouteRecordInfo<'/professional/change-password', '/professional/change-password', Record<never, never>, Record<never, never>>,
    '/professional/contact': RouteRecordInfo<'/professional/contact', '/professional/contact', Record<never, never>, Record<never, never>>,
    '/professional/edit-patient': RouteRecordInfo<'/professional/edit-patient', '/professional/edit-patient', Record<never, never>, Record<never, never>>,
    '/professional/infos': RouteRecordInfo<'/professional/infos', '/professional/infos', Record<never, never>, Record<never, never>>,
    '/professional/manual': RouteRecordInfo<'/professional/manual', '/professional/manual', Record<never, never>, Record<never, never>>,
    '/professional/new-test': RouteRecordInfo<'/professional/new-test', '/professional/new-test', Record<never, never>, Record<never, never>>,
    '/professional/patient-details': RouteRecordInfo<'/professional/patient-details', '/professional/patient-details', Record<never, never>, Record<never, never>>,
    '/professional/patients': RouteRecordInfo<'/professional/patients', '/professional/patients', Record<never, never>, Record<never, never>>,
    '/professional/profile': RouteRecordInfo<'/professional/profile', '/professional/profile', Record<never, never>, Record<never, never>>,
    '/professional/register-patient': RouteRecordInfo<'/professional/register-patient', '/professional/register-patient', Record<never, never>, Record<never, never>>,
    '/professional/terms-of-use': RouteRecordInfo<'/professional/terms-of-use', '/professional/terms-of-use', Record<never, never>, Record<never, never>>,
    '/professional/test-finished': RouteRecordInfo<'/professional/test-finished', '/professional/test-finished', Record<never, never>, Record<never, never>>,
    '/professional/test-progress': RouteRecordInfo<'/professional/test-progress', '/professional/test-progress', Record<never, never>, Record<never, never>>,
    '/professional/test-result': RouteRecordInfo<'/professional/test-result', '/professional/test-result', Record<never, never>, Record<never, never>>,
  }
}
