/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/edit-patient': RouteRecordInfo<'/edit-patient', '/edit-patient', Record<never, never>, Record<never, never>>,
    '/infos': RouteRecordInfo<'/infos', '/infos', Record<never, never>, Record<never, never>>,
    '/manual': RouteRecordInfo<'/manual', '/manual', Record<never, never>, Record<never, never>>,
    '/new-test': RouteRecordInfo<'/new-test', '/new-test', Record<never, never>, Record<never, never>>,
    '/patients': RouteRecordInfo<'/patients', '/patients', Record<never, never>, Record<never, never>>,
    '/register-patient': RouteRecordInfo<'/register-patient', '/register-patient', Record<never, never>, Record<never, never>>,
    '/sign-in': RouteRecordInfo<'/sign-in', '/sign-in', Record<never, never>, Record<never, never>>,
    '/test-finished': RouteRecordInfo<'/test-finished', '/test-finished', Record<never, never>, Record<never, never>>,
    '/test-progress': RouteRecordInfo<'/test-progress', '/test-progress', Record<never, never>, Record<never, never>>,
    '/test-result': RouteRecordInfo<'/test-result', '/test-result', Record<never, never>, Record<never, never>>,
  }
}
